### PR TITLE
fix: use eslint_d from none-ls-extras.nvim

### PR DESCRIPTION
**Pull request by mochaaP**
You need to ensure `eslint_d` is installed manually.

### CODE REVIEW

**Comment by mochaaP** [comment]
@GR3YH4TT3R93 I still don't understand why you are straight up playing dead here when I **directly** provide help, while still pushing on the rollback.

Yet, I still don't see any PRs to roll back the changes in <https://github.com/nvimtools/none-ls.nvim/commit/f81edad87bc6c1a4e675e8e97b22a62939ad4ade>. (hint: `git revert f81edad87 && git push` is not that hard)
If people actually wanted this, why no one had stand out to do this?

You can, still, pin to an older commit if you *really* disliked that change.

**Comment by GR3YH4TT3R93** [comment]
I'm not "playing dead" here, I said my peace. I saw that there are issues with this pr according to others in the discussion so I haven't merged it. I did pin to a previous commit until things are sorted out.

There's nothing more I can say or do without ruffling more feathers so I'm sitting this one out. I didn't even think to make a pr because I felt it would be just more toe-stepping and I'm not interested in whatever issues may arise from that. If others think that's the right thing/ acceptable thing to do, then I'll let them do it but it's clear that my contributions on this topic are not being conveyed or recieved in a positive manner so I will sit this one out. If it stays in, I'd be happy to contribute to fix any issues with eslint_d if they arise but there's nothing more I can contribute to the topic at hand. I'm sorry.

**Comment by mochaaP** [comment]
> *my contributions on this topic are not being conveyed or recieved in a positive manner*

Yeah, I believe those are positive contributions:

image

image

**Comment by GR3YH4TT3R93** [comment]
That's literally what "conveyed in a positive manner" means. Now please stop.

**Pull request closed without merging**
